language: csharp
solution: challenges.sln
mono: none
dotnet: 2.1

# Specify which branches can be built on PR merge
branches:
  only:
    - master
    - development

script:
- dotnet restore

notifications:
    slack: sem5640-2018:VcMGu78XPO237vvg9uH7mnNC
